### ISSUE TITLE
这个媒体库的封面没有文字的吗？

### ISSUE THREAD

**Issue by skywolf123** [clion007/docker-jellyfin#5]
原版的媒体库的封面是有文字的
![image](https://github.com/user-attachments/assets/d2fd2c39-3d99-4155-8c0d-60e992194404)
但是你这个好像是没有文字的，还是我哪里配置错了？
![image](https://github.com/user-attachments/assets/d00e92fb-a142-416f-acc6-6a66839f62bb)

**Comment by clion007** [comment]
新版本的jellyfin好像把封面文字去掉了
